




#######################

esphome:
  name: esp32-p4-tab7
  friendly_name: 7inch-tab
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: -100
    then: 
      - script.execute: inactivity_timer
      


text:
  - platform: template
    id: rwv_url
    name: "URL"
    optimistic: true
    restore_value: false
    mode: TEXT
    min_length: 1
    set_action:
      - lambda: |-
          if (!id(rwv).open_url(std::string(x.c_str()))) {
            id(rwv).set_url(std::string(x.c_str()));
            ESP_LOGI("remote_webview", "URL queued (not connected): %s", x.c_str());
          }




script:
  - id: inactivity_timer
    mode: restart
    then:
      - if:
          condition:
            light.is_off: back_light
          then:
            - light.turn_on:
                id: back_light
            - delay: 0.5s
           # - lambda: |-
             #   id(rwv).disable_touch(false);
      - delay: 15s
      - light.turn_off:
          id: back_light
      #- lambda: |-
       #   id(rwv).disable_touch(true);
                

  
          
button:
  

  - platform: restart 
    name: "Khởi động lại"
    id: restart_switch  
                  
          
safe_mode:


esp32:
  board: esp32-p4-evboard
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SPIRAM_XIP_FROM_PSRAM: y
      CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: n
      COMPILER_OPTIMIZATION_PERF: y # tối ưu tốc độ CPU
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_FREERTOS_UNICORE: n # đảm bảo dual-core hoạt động
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_360: y  # lock 360MHz

    advanced: 
      enable_idf_experimental_features: yes 
    components:
      - name: "espressif/esp_websocket_client"
        ref: 1.5.0
      - name: "bitbank2/jpegdec"
        source: https://github.com/SleepinDevil/jpegdec-esphome

#external_components:
#  - source: github://minhquanghp86/RemoteWebViewClient@main
#    refresh: 0s
 #   components: [ remote_webview ]

#external_components:
#  - source: github://strange-v/RemoteWebViewClient@hardware_jpeg
#    refresh: 0s
#    components: [ remote_webview ]

external_components:
  - source: 
      type: local
      path: components/remote_webview_p4


remote_webview:
  id: rwv
#  device_id: matouch-e32p4mi71
  server: 192.168.10.2:8081
  url: http://192.168.10.2:8123/dashboard-mobile/2 
  full_frame_tile_count: 1
  max_bytes_per_msg: 262144 #256k
  jpeg_quality: 80
  min_frame_interval: 50
  tile_size: 64 # not less
 

logger:
  level: WARN
  hardware_uart: USB_SERIAL_JTAG
  baud_rate: 115200

psram:
  mode: hex
  speed: 200MHz

debug:

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

time:
  
  - platform: sntp
    id: sntp_time
    timezone: Asia/Ho_Chi_Minh
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - time.google.com
    on_time_sync:
      then:
        # Write time to RTC
        - rx8130.write_time:
            id: rx8130_time

  - platform: rx8130
    id: rx8130_time            

wifi:
  ssid: XIAOMI
  password: "tukhongdenchin"
  manual_ip:
    static_ip: 192.168.10.179
    gateway: 192.168.10.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4

  ap:
    ssid: "REMOTE_WEBVIEW ESP32-P4"
    password: "12345678"


captive_portal:

#ethernet:
#  type: IP101
#  mdc_pin: GPIO31
#  mdio_pin: GPIO52
#  clk: 
#    pin: GPIO50
#    mode: CLK_EXT_IN
#  phy_addr: 1
#  power_pin: GPIO51

api:
  reboot_timeout: 0s
  homeassistant_services: true
 
ota:
  - platform: esphome

output:
  - id: backlight_output
    platform: ledc
    pin: GPIO23

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: back_light
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    gamma_correct: 1.0
    on_turn_on:
      then:
        - script.execute: inactivity_timer        

        

esp_ldo:
  - channel: 3
    id: dsi_phy_enable
    voltage: 2.5V
    adjustable: True
  - channel: 4
    id: sd_card_power
    voltage: 2.7V
    adjustable: True

display:
  - platform: mipi_dsi
    model: JC1060P470
    reset_pin: GPIO5
    update_interval: never
    id: main_display
  #  rotation: 0
    auto_clear_enabled: false
    hsync_pulse_width: 20



i2c:
  - id: i2c_bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz
    sda_pullup_enabled: False
    scl_pullup_enabled: False

touchscreen:
  - platform: gt911
    id: touchscreen_
    on_touch:
      then:

      - script.execute: inactivity_timer

    



audio_dac:
  - platform: es8311
    id: es8311_codec
    i2c_id: i2c_bus_a
    address: 0x18
    bits_per_sample: 16bit
    sample_rate: 44100
    use_mclk: True
    use_microphone: True
    mic_gain: 24DB

i2s_audio:
  - id: i2s_output
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
    i2s_mclk_pin: GPIO13

microphone:
  - platform: i2s_audio
    id: external_mic
    i2s_audio_id: i2s_output
    i2s_mode: primary
    adc_type: external
    i2s_din_pin: GPIO48
    sample_rate: 16000
    bits_per_channel: 16bit
    channel: stereo

speaker:
  - platform: i2s_audio
    i2s_audio_id: i2s_output
    id: speaker_id
    i2s_dout_pin: GPIO09
    dac_type: external
    sample_rate: 44100
    bits_per_sample: 16bit
    channel: left
    audio_dac: es8311_codec
    buffer_duration: 1000ms
    i2s_mode: primary
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
    num_channels: 1
    task_stack_in_psram: True
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input
  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input

media_player:
  - platform: speaker
    name: "Speaker Media Player"
    id: speaker_media_player_id
    task_stack_in_psram: True
    buffer_size: 1000000
    codec_support_enabled: True
    volume_initial: 70%
    volume_max: 70%
    announcement_pipeline:
        speaker: announcement_spk_resampling_input
        sample_rate: 44100
        num_channels: 1

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 5s
    
